apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secret
  namespace: default
type: Opaque
stringData:
  APP_KEY: "base64:5aYKS8MIZhgIcMts/PeWLrvbqWtcB9S1LfmejBLzjOk="
  JWT_SECRET: "rtpHvVnv9+I8HErEuYrSC6O2jujRrv2DDm4ENvY+s9PptYBe+hjYHBceLIQPUzLudl2T6gHrqphoSfAxR8pzzg=="
  DB_PASSWORD: "secret"
